name: Monthly Anniversary Invoice Job

on:
  schedule:
    - cron: "51 11 * * *" # Runs daily at 1:00 AM UTC
  workflow_dispatch: # Optional: allows manual trigger

jobs:
  run-monthly-invoice:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: backend # Ensure the working directory is set to the backend

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Install dependencies
        run: npm ci

      - name: Run invoice script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/monthlyAnniversaryInvoice.js
