name: Monthly Policy Billing

on:
  schedule:
    - cron: "0 3 * * *" # every day at 3 AM UTC
  workflow_dispatch:

jobs:
  run-invoicing:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - run: npm install

      - name: Run monthly invoice script
        env:
          SUPABASE_URL: ${{ secrets.SUPABASE_URL }}
          SUPABASE_SERVICE_ROLE_KEY: ${{ secrets.SUPABASE_SERVICE_ROLE_KEY }}
        run: node scripts/monthlyAnniversaryInvoice.js
